/**
 * This class is generated by jOOQ
 */
package org.cobraparser.db;

/**
 * Convenience access to all tables in PUBLIC
 */
@javax.annotation.Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.5.0"
    },
    comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

  /**
   * The table PUBLIC.PERMISSIONS
   */
  public static final org.cobraparser.db.tables.Permissions PERMISSIONS = org.cobraparser.db.tables.Permissions.PERMISSIONS;

  /**
   * The table PUBLIC.COOKIES
   */
  public static final org.cobraparser.db.tables.Cookies COOKIES = org.cobraparser.db.tables.Cookies.COOKIES;

  /**
   * The table PUBLIC.GLOBALS
   */
  public static final org.cobraparser.db.tables.Globals GLOBALS = org.cobraparser.db.tables.Globals.GLOBALS;
}
